trigger:
  branches:
    include:
    - daveta-funtest
    exclude:
    - master

variables:
  # Container registry service connection established during pipeline creation
  buildIdTag: $(Build.BuildNumber)
  webAppName: 'pyfuntest'
  resourceGroupName: 'pyfuntest'

jobs:
- job: Cleanup
  pool:
    vmImage: 'Ubuntu-16.04'
  
  steps:
  - task: AzureCLI@2
    displayName: Cleanup old resource group
    inputs:
      azureSubscription: 'FUSE Temporary (174c5021-8109-4087-a3e2-a1de20420569)'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az group delete --name $(resourceGroupName) -y
        az group create --location westus --name $(resourceGroupName)
    continueOnError: true
  - task: AzureCLI@2
    displayName: 'Provision/Deploy Bot'
    inputs:
      azureSubscription: 'FUSE Temporary (174c5021-8109-4087-a3e2-a1de20420569)'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        cd $(Build.SourcesDirectory)/libraries/functional-tests/functionaltestbot
        az webapp up --sku F1 -n $(webAppName) -l westus --resource-group $(resourceGroupName)
        az bot create --appid $(botAppId) --name $(webAppName) --password $(botAppPassword) --resource-group $(resourceGroupName) --sku F0 --kind registration --location westus --endpoint "https://pyfuntest.azurewebsites.net/api/messages"
        az webapp config appsettings set -g $(resourceGroupName) -n $(webAppName) --settings MicrosoftAppId=$(botAppId) MicrosoftAppPassword=$(botAppPassword) botId="pythonfunctional"
    continueOnError: false
  - task: AzureCLI@2
    displayName: 'Create DirectLine'
    inputs:
      azureSubscription: 'FUSE Temporary (174c5021-8109-4087-a3e2-a1de20420569)'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az bot directline create --name "pyfuntest" --resource-group "pyfuntest" > $(Agent.TempDirectory)/DirectLineConfig.json
    continueOnError: false
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'

  - bash: 'cp $(Build.SourcesDirectory)/libraries/functional-tests/functionaltestbot/tests/* $(Agent.TempDirectory)'
    workingDirectory: $(Agent.TempDirectory)
    displayName: 'Copy Tests'
    continueOnError: false

  - bash: 'python -m unittest test_py_bot.py'
    workingDirectory: $(Agent.TempDirectory)
    displayName: 'Run Test'
    continueOnError: false
    