trigger:
  branches:
    include:
    - daveta-funtest
    exclude:
    - master

variables:
  resourceGroupName: 'pyfuntest'

jobs:
- job: Doit
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - task: AzureCLI@2
    displayName: Provision, Deploy and run tests
    inputs:
      azureSubscription: 'FUSE Temporary (174c5021-8109-4087-a3e2-a1de20420569)'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        cd $(Build.SourcesDirectory)/libraries/functional-tests/functionaltestbot
        ./scripts/deploy_webapp.sh --appid $(botAppId) --password $(botAppPassword) -g $(resourceGroupName)
    continueOnError: false
